GET http://localhost:3000/courses/1/1 HTTP/1.1

###

GET http://localhost:3000/courses/1 HTTP/1.1

###

POST http://localhost:3000/courses HTTP/1.1
content-type: application/json

{
  "tutor_id": 1,
  "course_id": 3,
  "course_name": "Three course"
}

###

GET http://localhost:3000/health HTTP/1.1